# General
appname: notejam
env: prod
replicaCount: 2
port: 80
targetport: 8000

# Image
image:
  repository: sreejithpg
  name: notejam
  tag: "1.0.0"

# Service Account
serviceAccount:
  create: false
  name: "notejam"

# Ingress Resource
ingress: test4.example.com

# Resources
resources:
  limits:
    cpu: "20m"
    memory: "200Mi"
  requests:
    cpu: "10m"
    memory: "100Mi"

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
