apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    env: {{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }} 
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        env: {{ .Values.env }}
    spec:
      containers:
      - name: {{ .Values.appname }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8000
