apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  labels:
    app: {{ .Values.appname }}
    env: {{ .Values.env }}
  name: {{ .Values.appname }}-ingress
spec:
  rules:
  - host: {{ .Values.ingress }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.appname }}-svc
            port:
              number: 80
        path: /
        pathType: Prefix