apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: db
    app: wordpress
  name: mysql
spec:
  containers:
  - image: mysql
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Sannu123
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQSL_PASSWORD
      value: wordpress123
    ports:
    - containerPort: 3306
