apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    tier: web
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
  externalIPs:
  - 192.168.54.11 
