apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    tier: web
    app: wordpress
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
  type: LoadBalancer
